migrated to androidx
InflationX/Calligraphy pull request #10
Opened 2018-09-21 16:06 UTC by kibotu

2018-09-21 20:11 UTC, ZacSweers reviewed
Thanks for the PR! Looks like there's a few things going on here, so let's try to keep it a pure migration and keep functional changes to a separate discussion. Also please abide by the existing code style (formatting, nullability annotations)

2018-09-21 20:11 UTC, hzsweers commented on CHANGELOG.md
> +## 4.0.0 (21.8.2018)
Leave this out for now, maintainers will update the changelog when a new release is made

2018-09-21 20:11 UTC, hzsweers commented on CalligraphySample/build.gradle
> +    implementation 'com.github.kibotu:ViewPump:v2.0.0'
What's this?

2018-09-21 20:11 UTC, hzsweers commented on CalligraphySample/src/main/java/io/github/inflationx/calligraphy3/sample/MainActivity.java
> -            @Override public void run() {
Nit - don't change the style here

2018-09-21 20:11 UTC, hzsweers commented on CalligraphySample/src/main/java/io/github/inflationx/calligraphy3/sample/PlaceholderFragment.java
> +    public View onCreateView(@NonNull LayoutInflater inflater, ViewGroup container, Bundle state) {
This project assumes nonnull is the default, please only use nullable annotations as needed

2018-09-21 20:11 UTC, hzsweers commented on CalligraphySample/src/main/java/io/github/inflationx/calligraphy3/sample/TextField.java
> +public class TextField extends AppCompatTextView {
What's this change for?

2018-09-21 20:11 UTC, hzsweers commented on CalligraphySample/build.gradle
> +    debugImplementation 'com.squareup.leakcanary:leakcanary-android-no-op:1.5.4'
Latest is 1.6.0

2018-09-21 20:11 UTC, hzsweers commented on README.md
> +Calligraphy [![API](https://img.shields.io/badge/API-15%2B-brightgreen.svg?style=flat)](https://android-arsenal.com/api?level=14) [![Gradle Version](https://img.shields.io/badge/gradle-4.10.2-green.s
Let's keep this out

2018-09-21 20:11 UTC, hzsweers commented on build.gradle
> +    classpath 'com.github.dcendents:android-maven-gradle-plugin:2.1'
What's this?

2018-09-21 20:11 UTC, hzsweers commented on build.gradle
> +    classpath 'com.android.tools.build:gradle:3.3.0-alpha11'
Please use the latest stable

2018-09-21 20:11 UTC, hzsweers commented on build.gradle
> -task wrapper(type: Wrapper) {
Why remove this vs update it?

2018-09-21 20:11 UTC, hzsweers commented on build.gradle
> +    maven { url 'https://jitpack.io' }
What's this for?

2018-09-21 20:11 UTC, hzsweers commented on calligraphy/build.gradle
> +//apply from: rootProject.file('gradle/deploy.gradle')
Why is this commented?

2018-11-14 20:49 UTC, jbarr21 requested changes
please address remaining feedback

2018-11-14 20:56 UTC, jbarr21 commented
Thanks for your contribution! I've made the changes for the comments that were requested and have merged it manually into master.

2018-11-14 20:56 UTC, closed without merging